const http = 'http://localhost:7500';
export const UPDATE_OR_DELETE = `${http}/book/update_or_delete`;
export const CREATE_UPDATE_ANY = `${http}/book/create/update/any`;
export const GET_BOOK_FROM_ID = (bookId: string) => `${http}/book/getall/${bookId}`;
export const GET_BOOK_ALL = `${http}/book/all`;
export const CREATE_NEW_BOOK = `${http}/book/create/new/book`;
export const LOGOUT = `${http}/logout`;
export const LOGIN = `${http}/login`;
export const SIGNUP = `${http}/signup`;
export const USER_SESSION = `${http}/user/session`;
export default null;