enum BOOK_SERVICE {
    API_STATE = 'API_STATE',
    API_DATA = 'API_DATA',
    SETTER = 'SETTER',
    SETTERS = 'SETTERS',
    FORM_PAGE_SETTER = 'FORM_PAGE_SETTER',
    ACTIVE_PAGE = 'ACTIVE_PAGE'
}

export { BOOK_SERVICE };